### ISSUE TITLE
vim hang for 1-2 seconds (or sometime more) on exit

### ISSUE THREAD

**Issue by louisgv** [sunaku/.vim#8]
Thanks for creating this great setup. I need some help fixing this hanging issue when exiting vim. I tried it on js files as well as markdown files and both have the same problem. See the gif below:

![output](https://user-images.githubusercontent.com/6723574/61983262-8f9e4880-afb4-11e9-87f5-837d726bf799.gif)

Let me know how I can dump more log. Thank you!

**Comment by louisgv** [comment]
After further investigation with a json file, it seems the problem was that the fix-json plugin was throwing a bunch of warning or is being installed everytime I exit out?

**Comment by louisgv** [comment]
I got this from editing a json file:
```
vim package.json                                                           ✹ ✭

{'throwpoint': 'function fixjson#format[2]..fixjson#format_async[4]..<SNR>312_new[5]..<SNR>310_start_format_job[2]..<SNR>310_build_command[1]..<SNR>310_ensure_command[10]..fixjson#npm#local_command[2]..fixjson#npm#install, line 8', 'exception': 'Failed to install fixjson by ''cd ''/home/jojo/.vim/ftbundle/json/fixjson'' && npm install --no-package-lock fixjson'': npm WARN jojo No description^@npm WARN jojo No repository field.^@npm WARN jojo No license field.^@^@+ fixjson@1.1.0^@updated 1 package and audited 74 packages in 2.158s^@found 0 vulnerabilities^@^@'}
gutentags: ctags job failed, returned: 1%     
```

**Comment by louisgv** [comment]
More log after editting a js file:
![image](https://user-images.githubusercontent.com/6723574/61984023-81056080-afb7-11e9-8da2-e65803738049.png)

**Comment by sunaku** [comment]
Looks like ALE was trying to install the fixjson package from NPM since it wasn't already installed on your system.  This was the cause of the delay when the file was being written before quitting Vim (`:x`).

If you don't need this JSON fixing facility, it would be easiest to remove it by running `bin/delete fixjson`

Otherwise, you can run `npm install -g fixjson` once outside of Vim to prevent ALE from delaying.

**Comment by louisgv** [comment]
I tried to delete fixjson and there still seems to be a 1-2 seconds delay when I `:x` out of vim

**Comment by sunaku** [comment]
Strange, I'm unable to reproduce the issue here (both with and without the `fixjson` bundle installed).

I even tested with a [larger JSON file contents](https://github.com/sharegate/craco/blob/master/packages/craco/README.md#configuration-overview) than what's in your screencast, but my `:x` is still fast. :thinking:

**Comment by louisgv** [comment]
I tested again with vim package.json -V9vim.log and below is the gist:

https://gist.github.com/louisgv/0c7472c23e536369ca57b4f3b96d5a80

Strangely, when tested on a file outside my project directory, `:x` and `:q` were fine. Based on the log above, it seems there were something trying to crawl through my workspace? Would love to hear your insight on the log. Thank you for your help!

**Comment by sunaku** [comment]
Good suggestions! :+1:  I think you're on the right track:  [Gutentags](https://github.com/ludovicchabant/vim-gutentags) might be causing the delay upon exit.

Try creating a `.notags` file (see `:help gutentags-.notags`) in your project directory and restart vim:

```sh
touch .notags
```

**Comment by louisgv** [comment]
I have added `.notags` to both pwd and the root of my workspace (I'm using https://github.com/lerna/lerna ), but the log result is still quite big and it still hang for about 1-2 seconds:
https://gist.github.com/louisgv/d1b129fb871d872407b41cf72f073cd9

**Comment by louisgv** [comment]
Fixed! I forgot to remove the tags file themselves. Once I did that, `:q` is now instantly again. Thank you very much for your help :+1: :pray:
